const PROFILE_PICTURE_SIZE = 150;
const COLLECTION_COVER_SIZE = 250;
const MEDIA_IMAGE_SIZE = 1050;

export const constants = {
  PROFILE_PICTURE_SIZE,
  COLLECTION_COVER_SIZE,
  MEDIA_IMAGE_SIZE,
};
