export enum StorageKeys {
  CURRENT_USER = 'CURRENT_USER',
  AUTHENTICATED_USERS = 'AUTHENTICATED_USERS',
  NOTIFICATION_PUSH_REMINDED = 'NOTIFICATION_PUSH_REMINDED',
  NOTIFICATION_PUSH_TOKEN = 'NOTIFICATION_PUSH_TOKEN',
  PUBLIC_KEY = 'PUBLIC_KEY',
  PRIVATE_KEY = 'PRIVATE_KEY',
  MESSAGING_CREDENTIALS = 'MESSAGING_CREDENTIALS',
  CAMERA_PERMISSION_REMINDED = 'CAMERA_PERMISSION_REMINDED',
  MEDIA_PERMISSION_REMINDED = 'MEDIA_PERMISSION_REMINDED',
}
